import { Injectable } from '@nestjs/common';
import { AuditLogService } from '../../../../infrastructure/audit/audit-log.service';
import { BrainContext } from '../../../../infrastructure/ai-brain/brain-context.types';
import { ContextAssemblyService } from '../../../../infrastructure/ai-brain/context-assembly.service';
import { ResilientLlmGateway } from '../../../../infrastructure/ai-brain/resilient-llm-gateway.service';
import { LlmGatewayResult } from '../../../../infrastructure/ai-brain/resilient-llm-gateway.types';
import { MetricsService } from '../../../../infrastructure/observability/metrics.service';
import { ExplainabilityRulesService } from '../../../../shared/services/explainability-rules.service';
import {
  MISSION_FALLBACK_VERSION,
  MissionPlanningEngine,
} from '../../domain/engine/mission-planning.engine';
import { MissionTask } from '../../domain/engine/mission-planning.types';
import { buildMissionPrompt, MISSION_PROMPT_VERSION } from '../prompts/mission-prompt';
import { MissionPlanRequest, MissionPlanResponse } from '../contracts/mission-planner.contracts';

const CAPABILITY = 'mission_planner';
const DEFAULT_PROVIDER = 'mock-llm';
const DEFAULT_MODEL = 'mock-llm-v1';
const VALID_TASK_SOURCES = ['roadmap', 'recommendation', 'review'];

/**
 * Mission Planner capability. Reads context only through ContextAssemblyService,
 * reaches the LLM only through ResilientLlmGateway, and always has a
 * deterministic fallback (MissionPlanningEngine) so a mission is produced even
 * when the LLM path is unavailable or returns untrustworthy output.
 */
@Injectable()
export class MissionPlannerService {
  private readonly fallbackEngine = new MissionPlanningEngine();

  constructor(
    private readonly contextAssembly: ContextAssemblyService,
    private readonly llmGateway: ResilientLlmGateway,
    private readonly explainabilityRules: ExplainabilityRulesService,
    private readonly metrics?: MetricsService,
    private readonly auditLog?: AuditLogService,
  ) {}

  async generateTodaysMission(request: MissionPlanRequest): Promise<MissionPlanResponse> {
    const start = Date.now();
    const provider = request.provider ?? DEFAULT_PROVIDER;
    const model = request.model ?? DEFAULT_MODEL;

    try {
      const context = await this.contextAssembly.assemble({
        userId: request.userId,
        goalId: request.goalId,
        sessionId: request.sessionId,
        traceId: request.traceId,
      });

      const gatewayResult = await this.llmGateway.complete({
        capability: CAPABILITY,
        provider,
        model,
        prompt: buildMissionPrompt(context),
        promptVersion: MISSION_PROMPT_VERSION,
      });

      const response = gatewayResult.fallbackUsed
        ? this.buildFallbackResponse(context, gatewayResult)
        : this.buildLlmResponse(context, gatewayResult);

      this.explainabilityRules.validate({
        confidence: response.confidence,
        reasoning: response.explanation,
        traced_to: [
          `goal:${context.goalId}`,
          `roadmap:${context.roadmap.nodeId}`,
          `session:${context.sessionId}`,
        ],
      });

      await this.emitObservability(request, response, start, 'SUCCESS');
      return response;
    } catch (error) {
      await this.emitObservability(request, null, start, 'FAILURE', error);
      throw error;
    }
  }

  private buildFallbackResponse(
    context: BrainContext,
    gatewayResult: LlmGatewayResult,
  ): MissionPlanResponse {
    const plan = this.fallbackEngine.generate(context);
    return {
      ...plan,
      confidence: 0.5,
      explanation: `Deterministic fallback (${MISSION_FALLBACK_VERSION}) used because: ${gatewayResult.fallbackReason ?? 'unknown'}.`,
      provider: gatewayResult.provider,
      model: gatewayResult.model,
      fallbackUsed: true,
      promptVersion: MISSION_PROMPT_VERSION,
    };
  }

  private buildLlmResponse(
    context: BrainContext,
    gatewayResult: LlmGatewayResult,
  ): MissionPlanResponse {
    const raw = (gatewayResult.raw ?? {}) as Record<string, unknown>;
    const tasks = this.normalizeTasks(raw.tasks, context);

    if (!tasks) {
      return this.buildFallbackResponse(context, {
        ...gatewayResult,
        fallbackUsed: true,
        fallbackReason: 'invalid_llm_output',
      });
    }

    return {
      missionId: `mission-${context.goalId}-${context.assembledAt}`,
      goalId: context.goalId,
      sessionId: context.sessionId,
      date: context.assembledAt.slice(0, 10),
      tasks,
      focusSummary:
        typeof raw.focusSummary === 'string' && raw.focusSummary.trim().length > 0
          ? raw.focusSummary
          : 'Mission generated by LLM',
      confidence: this.normalizeConfidence(raw.confidence),
      explanation:
        typeof raw.reasoning === 'string' && raw.reasoning.trim().length > 0
          ? raw.reasoning
          : 'No reasoning provided by model',
      provider: gatewayResult.provider,
      model: gatewayResult.model,
      fallbackUsed: false,
      promptVersion: MISSION_PROMPT_VERSION,
    };
  }

  private normalizeTasks(value: unknown, context: BrainContext): MissionTask[] | null {
    if (!Array.isArray(value) || value.length === 0) return null;

    return value.map((raw, index) => {
      const t = (raw ?? {}) as Record<string, unknown>;
      return {
        id: typeof t.id === 'string' && t.id.trim().length > 0 ? t.id : `${context.goalId}-task-${index}`,
        title: typeof t.title === 'string' && t.title.trim().length > 0 ? t.title : 'Untitled task',
        description: typeof t.description === 'string' ? t.description : '',
        estimatedMinutes: typeof t.estimatedMinutes === 'number' ? t.estimatedMinutes : 15,
        source: VALID_TASK_SOURCES.includes(t.source as string)
          ? (t.source as MissionTask['source'])
          : 'review',
      };
    });
  }

  private normalizeConfidence(value: unknown): number {
    if (typeof value !== 'number' || Number.isNaN(value)) return 0;
    if (value < 0) return 0;
    if (value > 1) return 1;
    return value;
  }

  private async emitObservability(
    request: MissionPlanRequest,
    response: MissionPlanResponse | null,
    startMs: number,
    status: 'SUCCESS' | 'FAILURE',
    error?: unknown,
  ): Promise<void> {
    console.log(
      JSON.stringify({
        traceId: request.traceId,
        operation: 'GENERATE_MISSION',
        capability: CAPABILITY,
        goalId: request.goalId,
        sessionId: request.sessionId,
        latencyMs: Date.now() - startMs,
        status,
        fallbackUsed: response?.fallbackUsed,
        confidence: response?.confidence,
        errorType: error instanceof Error ? error.constructor.name : undefined,
        timestamp: new Date().toISOString(),
      }),
    );

    if (status !== 'SUCCESS' || !response) return;

    this.metrics?.incrementMissionPlanGenerated();
    this.metrics?.recordMissionPlanConfidence(response.confidence);
    if (response.fallbackUsed) {
      this.metrics?.incrementMissionPlanFallbackUsed();
    }

    await this.auditLog
      ?.recordSecurityEvent({
        traceId: request.traceId,
        userId: request.userId,
        operation: 'MISSION_PLAN_GENERATED',
        resource: `Mission:${response.missionId}`,
        after: {
          fallbackUsed: response.fallbackUsed,
          provider: response.provider,
          model: response.model,
          promptVersion: response.promptVersion,
          confidence: response.confidence,
          taskCount: response.tasks.length,
        },
      })
      .catch(() => undefined);
  }
}
