import { Injectable } from '@nestjs/common';

@Injectable()
export class MockLlmClientService {
  async complete(prompt: string): Promise<Record<string, unknown>> {
    if (prompt.includes('TRIGGER_INVALID_JSON')) {
      return { action: 'reply', response: 'invalid without explainability' };
    }

    return {
      action: 'reply',
      response: 'Generated by AI runtime',
      confidence: 0.86,
      reasoning: 'Context and routing signals indicate this response path.',
      traced_to: ['goal:goal-1', 'session:session-1', 'roadmap:node-1', 'evidence:ev-1', 'assessment:as-1']
    };
  }
}
