export enum MessageStatus {
  CREATED = 'CREATED',
  QUEUED = 'QUEUED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  DEAD_LETTER = 'DEAD_LETTER',
}
