import { MessagePriority } from './message-priority';
import { MessageType } from './message-types';

/**
 * Caller-supplied fields for MessageBusService.publish(). Every other
 * AgentMessage field (messageId, timestamps, status, retryCount) is
 * generated by the bus itself so publishers never fabricate delivery state.
 */
export interface MessageEnvelope {
  traceId: string;
  workflowId?: string | null;
  senderAgentId: string;
  receiverAgentId: string;
  messageType: MessageType;
  priority?: MessagePriority;
  payload: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}
