-- =====================================================================
-- SQL BATCH 1 — IDENTITY + GOAL + ROADMAP
-- AI Mentor OS — PostgreSQL / Supabase
--
-- Scope: learner, goal, roadmap, roadmap_node, approval_record,
-- history.learner. This is a SUBSET of DDL Round 1 — the Learning
-- Session Module (learning_session, sub_session,
-- learning_session_transition) is explicitly OUT of scope for this
-- batch (per the batch's own table list) and is deferred to its own
-- batch. No entity outside this list is created here.
--
-- Requires SQL_BATCH0_INFRASTRUCTURE.sql to have already run
-- (fn_set_updated_at, fn_increment_version_number, fn_write_history,
-- schema `history`, extension `pgcrypto`).
--
-- No RLS policy is created in this batch (Batch 6 scope).
--
-- Source of authority: DDL_ROUND1_DESIGN.md mục 1.1-1.5,
-- DatabaseNamingConvention.md, DECISION-043, DECISION-044, DECISION-045,
-- DECISION-047, DECISION-050.
-- =====================================================================


-- =====================================================================
-- 1. learner
-- =====================================================================
-- Current State Snapshot. id is NOT generated by this table — it is
-- shared 1:1 with auth.users.id (DECISION-043). No DEFAULT on id:
-- Supabase Auth assigns the value; this table only stores the
-- AI-Mentor-OS-specific profile columns for that same identity.
-- =====================================================================

CREATE TABLE public.learner (
  id                      uuid        NOT NULL,
  anonymized_at           timestamptz NULL,
  version_number          bigint      NOT NULL DEFAULT 1,
  created_at              timestamptz NOT NULL DEFAULT now(),
  created_by_actor_type   text        NOT NULL DEFAULT 'learner',
  created_by_actor_id     uuid        NULL,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  updated_by_actor_type   text        NOT NULL DEFAULT 'learner',
  updated_by_actor_id     uuid        NULL,

  CONSTRAINT pk_learner PRIMARY KEY (id),

  CONSTRAINT fk_learner_id_auth_users
    FOREIGN KEY (id) REFERENCES auth.users (id)
    ON DELETE RESTRICT,

  CONSTRAINT ck_learner_created_by_actor_type
    CHECK (created_by_actor_type IN ('learner', 'backend_core', 'ai_service')),

  CONSTRAINT ck_learner_updated_by_actor_type
    CHECK (updated_by_actor_type IN ('learner', 'backend_core', 'ai_service'))
);

COMMENT ON TABLE public.learner IS
  'Identity Module. id shared 1:1 with auth.users.id (DECISION-043) — the one exception to the <table>_id PK naming rule. anonymized_at NULL = active, NOT NULL = Right-to-be-Forgotten anonymized (DECISION-037).';

-- Triggers
CREATE TRIGGER trg_learner_set_updated_at
  BEFORE UPDATE ON public.learner
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_set_updated_at();

CREATE TRIGGER trg_learner_increment_version_number
  BEFORE UPDATE ON public.learner
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_increment_version_number();

CREATE TRIGGER trg_learner_write_history
  AFTER UPDATE ON public.learner
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_write_history();


-- =====================================================================
-- 2. history.learner
-- =====================================================================
-- Trigger-maintained history table (DECISION-045). HARD CONTRACT with
-- fn_write_history() (SQL_BATCH0_INFRASTRUCTURE.sql): column list must
-- mirror public.learner exactly, in the exact same order, followed by
-- exactly one trailing column `valid_from`. Do not reorder, do not
-- insert any column between the mirrored columns and valid_from, do
-- not add a leading surrogate PK column — fn_write_history() inserts
-- positionally via `SELECT (OLD).*, now()`.
--
-- No FK back to public.learner — this is an independent historical
-- log, not a dependent business entity; insertion is trigger-controlled
-- only, never by arbitrary application INSERT, so referential
-- protection at this table would be redundant.
--
-- No PRIMARY KEY constraint: id repeats across multiple history rows
-- for the same learner over time, and valid_from is NOT guaranteed
-- unique per id within a single transaction (see SQL_BATCH1_REVIEW.md
-- Risk #1 — now() is transaction-frozen in PostgreSQL). Supporting
-- (non-unique) indexes only.
-- =====================================================================

CREATE TABLE history.learner (
  id                      uuid        NOT NULL,
  anonymized_at           timestamptz NULL,
  version_number          bigint      NOT NULL,
  created_at              timestamptz NOT NULL,
  created_by_actor_type   text        NOT NULL,
  created_by_actor_id     uuid        NULL,
  updated_at              timestamptz NOT NULL,
  updated_by_actor_type   text        NOT NULL,
  updated_by_actor_id     uuid        NULL,
  valid_from              timestamptz NOT NULL
);

COMMENT ON TABLE history.learner IS
  'Trigger-maintained history of public.learner (DECISION-045). Column list mirrors public.learner exactly + trailing valid_from. Maintained exclusively by trg_learner_write_history — never insert into this table manually.';

CREATE INDEX ix_history_learner_id ON history.learner (id);
CREATE INDEX ix_history_learner_valid_from ON history.learner (valid_from);


-- =====================================================================
-- 3. goal
-- =====================================================================
-- Append-only / immutable (DECISION-032 — Goal never mutated; a new
-- Goal supersedes the old one).
-- =====================================================================

CREATE TABLE public.goal (
  goal_id                 uuid        NOT NULL DEFAULT gen_random_uuid(),
  learner_id              uuid        NOT NULL,
  statement               text        NOT NULL,
  supersedes_goal_id      uuid        NULL,
  created_at              timestamptz NOT NULL DEFAULT now(),
  created_by_actor_type   text        NOT NULL,
  created_by_actor_id     uuid        NULL,

  CONSTRAINT pk_goal PRIMARY KEY (goal_id),

  CONSTRAINT fk_goal_learner_id
    FOREIGN KEY (learner_id) REFERENCES public.learner (id)
    ON DELETE RESTRICT,

  CONSTRAINT fk_goal_supersedes_goal_id
    FOREIGN KEY (supersedes_goal_id) REFERENCES public.goal (goal_id)
    ON DELETE RESTRICT,

  CONSTRAINT ck_goal_no_self_supersede
    CHECK (supersedes_goal_id IS NULL OR supersedes_goal_id <> goal_id),

  CONSTRAINT ck_goal_created_by_actor_type
    CHECK (created_by_actor_type IN ('learner', 'backend_core', 'ai_service'))
);

COMMENT ON TABLE public.goal IS
  'Goal Module. Append-only/immutable (DECISION-032). supersedes_goal_id links a new Goal to the one it replaces — no UPDATE ever occurs on an existing row.';

CREATE INDEX ix_goal_learner_id ON public.goal (learner_id);
CREATE INDEX ix_goal_supersedes_goal_id ON public.goal (supersedes_goal_id);


-- =====================================================================
-- 4. roadmap
-- =====================================================================
-- Current State Snapshot. Protected by approval_record as companion
-- log (DECISION-045) — no version_number, no history table.
-- =====================================================================

CREATE TABLE public.roadmap (
  roadmap_id              uuid        NOT NULL DEFAULT gen_random_uuid(),
  goal_id                 uuid        NOT NULL,
  created_at              timestamptz NOT NULL DEFAULT now(),
  created_by_actor_type   text        NOT NULL,
  created_by_actor_id     uuid        NULL,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  updated_by_actor_type   text        NOT NULL,
  updated_by_actor_id     uuid        NULL,

  CONSTRAINT pk_roadmap PRIMARY KEY (roadmap_id),

  CONSTRAINT fk_roadmap_goal_id
    FOREIGN KEY (goal_id) REFERENCES public.goal (goal_id)
    ON DELETE RESTRICT,

  CONSTRAINT uq_roadmap_goal_id UNIQUE (goal_id),

  CONSTRAINT ck_roadmap_created_by_actor_type
    CHECK (created_by_actor_type IN ('learner', 'backend_core', 'ai_service')),

  CONSTRAINT ck_roadmap_updated_by_actor_type
    CHECK (updated_by_actor_type IN ('learner', 'backend_core', 'ai_service'))
);

COMMENT ON TABLE public.roadmap IS
  'Roadmap Module. 1:1 with goal (uq_roadmap_goal_id). Structural changes go through approval_record, not direct content columns — no version_number/history table needed (DECISION-045).';

-- uq_roadmap_goal_id already provides a unique index on goal_id.

CREATE TRIGGER trg_roadmap_set_updated_at
  BEFORE UPDATE ON public.roadmap
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_set_updated_at();


-- =====================================================================
-- 5. roadmap_node
-- =====================================================================
-- Current State Snapshot. Tree structure via self-referencing FK.
-- Protected by approval_record as companion log — no version_number,
-- no history table.
-- =====================================================================

CREATE TABLE public.roadmap_node (
  roadmap_node_id           uuid        NOT NULL DEFAULT gen_random_uuid(),
  roadmap_id                uuid        NOT NULL,
  parent_roadmap_node_id    uuid        NULL,
  title                     text        NOT NULL,
  node_status               text        NOT NULL DEFAULT 'collapsed',
  sort_order                integer     NOT NULL,
  created_at                timestamptz NOT NULL DEFAULT now(),
  created_by_actor_type     text        NOT NULL,
  created_by_actor_id       uuid        NULL,
  updated_at                timestamptz NOT NULL DEFAULT now(),
  updated_by_actor_type     text        NOT NULL,
  updated_by_actor_id       uuid        NULL,

  CONSTRAINT pk_roadmap_node PRIMARY KEY (roadmap_node_id),

  CONSTRAINT fk_roadmap_node_roadmap_id
    FOREIGN KEY (roadmap_id) REFERENCES public.roadmap (roadmap_id)
    ON DELETE CASCADE,

  CONSTRAINT fk_roadmap_node_parent_roadmap_node_id
    FOREIGN KEY (parent_roadmap_node_id) REFERENCES public.roadmap_node (roadmap_node_id)
    ON DELETE CASCADE,

  -- Proposed in DDL_ROUND1_DESIGN.md mục 1.4 — NOT yet confirmed by a
  -- Decision Log entry (Risk #7: Founder may want to allow sibling
  -- nodes sharing sort_order for "parallel" content). Implemented here
  -- as designed; see SQL_BATCH1_REVIEW.md for the open item.
  CONSTRAINT uq_roadmap_node_roadmap_id_parent_roadmap_node_id_sort_order
    UNIQUE (roadmap_id, parent_roadmap_node_id, sort_order),

  CONSTRAINT ck_roadmap_node_no_self_parent
    CHECK (parent_roadmap_node_id IS NULL OR parent_roadmap_node_id <> roadmap_node_id),

  CONSTRAINT ck_roadmap_node_status
    CHECK (node_status IN ('collapsed', 'expanded', 'completed')),

  CONSTRAINT ck_roadmap_node_sort_order_non_negative
    CHECK (sort_order >= 0),

  CONSTRAINT ck_roadmap_node_created_by_actor_type
    CHECK (created_by_actor_type IN ('learner', 'backend_core', 'ai_service')),

  CONSTRAINT ck_roadmap_node_updated_by_actor_type
    CHECK (updated_by_actor_type IN ('learner', 'backend_core', 'ai_service'))
);

COMMENT ON TABLE public.roadmap_node IS
  'Roadmap Module. Tree via parent_roadmap_node_id (self-reference, CASCADE within Roadmap Aggregate). roadmap_node ↔ knowledge_node M:N dependency edge added in a later batch (DDL Round 3, roadmap_node_knowledge_node) — not in this batch.';

CREATE INDEX ix_roadmap_node_roadmap_id ON public.roadmap_node (roadmap_id);
CREATE INDEX ix_roadmap_node_parent_roadmap_node_id ON public.roadmap_node (parent_roadmap_node_id);

CREATE TRIGGER trg_roadmap_node_set_updated_at
  BEFORE UPDATE ON public.roadmap_node
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_set_updated_at();


-- =====================================================================
-- 6. approval_record
-- =====================================================================
-- Append-only / immutable. approval_record_id is generated at the
-- Application Layer (ULID-style) — no DEFAULT here, the application
-- must always supply it.
-- =====================================================================

CREATE TABLE public.approval_record (
  approval_record_id        uuid        NOT NULL,
  roadmap_id                 uuid        NOT NULL,
  roadmap_node_id             uuid        NULL,
  change_description         text        NOT NULL,
  approved_by_learner_id      uuid        NOT NULL,
  approved_at                 timestamptz NOT NULL DEFAULT now(),
  created_by_actor_type       text        NOT NULL,
  created_by_actor_id         uuid        NULL,
  created_at                  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_approval_record PRIMARY KEY (approval_record_id),

  CONSTRAINT fk_approval_record_roadmap_id
    FOREIGN KEY (roadmap_id) REFERENCES public.roadmap (roadmap_id)
    ON DELETE RESTRICT,

  CONSTRAINT fk_approval_record_roadmap_node_id
    FOREIGN KEY (roadmap_node_id) REFERENCES public.roadmap_node (roadmap_node_id)
    ON DELETE RESTRICT,

  CONSTRAINT fk_approval_record_approved_by_learner_id
    FOREIGN KEY (approved_by_learner_id) REFERENCES public.learner (id)
    ON DELETE RESTRICT,

  CONSTRAINT ck_approval_record_created_by_actor_type
    CHECK (created_by_actor_type IN ('learner', 'backend_core', 'ai_service'))
);

COMMENT ON TABLE public.approval_record IS
  'Roadmap Module — companion log for roadmap/roadmap_node structural changes (DECISION-006, DECISION-045). roadmap_node_id NULL = change applies to the whole structure, not one node. approval_record_id generated at the Application Layer (ULID-style) — never relies on a DB DEFAULT.';

CREATE INDEX ix_approval_record_roadmap_id ON public.approval_record (roadmap_id);
CREATE INDEX ix_approval_record_roadmap_node_id ON public.approval_record (roadmap_node_id);
CREATE INDEX ix_approval_record_approved_by_learner_id ON public.approval_record (approved_by_learner_id);


-- =====================================================================
-- END OF BATCH 1
--
-- Result after this batch:
--   - 5 business tables: learner, goal, roadmap, roadmap_node,
--     approval_record
--   - 1 history table: history.learner
--   - 5 trigger attachments (3 on learner, 1 on roadmap, 1 on
--     roadmap_node)
--   - 8 indexes (+ 1 unique index from uq_roadmap_goal_id, + 1 unique
--     index from uq_roadmap_node_roadmap_id_parent_roadmap_node_id_sort_order)
--   - zero RLS policies
--   - zero tables outside the 6 listed in scope (Learning Session
--     Module deferred)
--
-- Next: Batch for Learning Session Module (learning_session,
-- sub_session, learning_session_transition), then Batch 2 (DDL Round 2).
-- =====================================================================
