export enum MigrationStatus {
  PLANNED = 'PLANNED',
  VALIDATING = 'VALIDATING',
  EXECUTING = 'EXECUTING',
  VERIFYING = 'VERIFYING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ROLLED_BACK = 'ROLLED_BACK'
}
