export enum MigrationState {
  PENDING = 'PENDING',
  VALIDATING = 'VALIDATING',
  EXECUTING = 'EXECUTING',
  VERIFYING = 'VERIFYING',
  COMMITTED = 'COMMITTED',
  FAILED = 'FAILED',
  ROLLED_BACK = 'ROLLED_BACK'
}
